Feature/user profile
ESinco/frontend pull request #29
Opened 2024-08-14 12:14 UTC by fernandocandeiatorres

2024-08-15 18:34 UTC, YoYolops requested changes
Salve Fernando.
Excelente solução!
Fiz algumas sugestões principalmente a respeito de estilizações e o cuidado que se deve ter com componentes compartilhados que usam margens (Eles causam muito caos quando precisam ser usados em múltiplas páginas)

Importante mencionar também que o padrão inglês que conversamos em reuniões não foram implementados apropriadamente, ainda existem componentes nomeados em português!

As alterações mais chatas de fazer, eu mesmo fiz! Tá na branch `reviews`, recomendo que a clone, faça merge com a sua (não antes de analisar bem o que foi alterado) e aplique as alterações pendentes!

2024-08-15 18:34 UTC, YoYolops commented on src/components/ExperienciasCard.js
Aqui a gente tem alguns problemas. Os cards estão fora de padrão e se comportando mal sob redimensionamento de telas. Grande parte disso se deve ao uso confuso de paddings e margins.
Componentes que vão ser renderizados por outros se beneficiam muito de não usar margens na tag mais exterior.

Repara que ali na linha 5, você aplicou uma `margin-y`. Isso é problema por que gera dificuldades de estilização e posicionamento na página que vai usar aquele componente. Vamos evitar isso!

Do jeito que está, os cards ficam completamente quebrados com a extensão da tela (Apesar de o figma estar focado na visão mobile, o app deve ser comportar bem em grandes telas):

![Captura de tela de 2024-08-15 15-04-26](https://github.com/user-attachments/assets/399eec60-c548-4b0f-924c-cf0d80627120)

Organizando um pouco os `paddings`, mudando `justify`s etc:

![Captura de tela de 2024-08-15 15-07-49](https://github.com/user-attachments/assets/3965d199-8122-4769-b32f-6958a14a2041)

2024-08-15 18:34 UTC, YoYolops commented on src/components/ExperienciasCard.js
Mais um comentário sobre as widths: Usando a mesma lógica das margens, as widths deveriam ser sempre 100%, dando à pagina que vai usar o componente a possibilidade de alterar sua largura como desejar. Como? através de tags "slots" (não é um termo oficial).
Um slot seria apenas uma div que envolveria o componente e o espremeria, aplicaria margins etc:

```html
<div className="mt-10 w-11/12">
    <MeuComponente />
</div>
```

2024-08-15 18:34 UTC, YoYolops commented on src/components/HabilidadesCard.js
Problemas parecidos com os de `<ExperienciasCard />`

2024-08-16 12:26 UTC, fernandocandeiatorres commented on src/components/ExperienciasCard.js
Genial essa dica dos slots e da margin, estou refatorando aqui.

2024-08-16 21:32 UTC, YoYolops approved these changes

2024-08-16 21:33 UTC, merged